name: opensarlab_mintpy_recipe_book
channels:
  - conda-forge
dependencies:
  - python=3.11
  - asf_search 
  - bokeh
  - boto3
  - cartopy
  - contextily
  - dask
  - distributed
  - gdal
  - geopandas
  - h5py
  - hyp3_sdk
  - ipyfilechooser
  - numpy
  - pandas
  - pip
  - pyaps3==0.3.5 #0.3.6 CDS downloads fail from MintPy
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - pip:
    - opensarlab_lib
    - git+https://github.com/insarlab/MintPy.git@4bbca8c
    - jupyterlab==4.1.5
    - notebook==7.1.3
    - matplotlib==3.8.4
    - ipympl==0.9.2
    - ipywidgets==8.1.2
    - jupyterlab-widgets==3.0.10
    - widgetsnbextension==4.0.10

