name: opensarlab_mintpy_recipe_book
channels:
  - conda-forge
dependencies:
  - python==3.9
  - asf_search 
  - bokeh==3.4.1 # 3.4.2 breaks distributed<=2023.4.1
  - boto3
  - cartopy
  - contextily
  - dask
  - distributed<=2023.4.1 # later versions require Python>=3.10
  - gdal
  - geopandas
  - h5py
  - hyp3_sdk
  - ipympl
  - ipyfilechooser
  - jupyterlab
  - ipywidgets
  - matplotlib-base
  - mintpy
  - numpy
  - pandas
  - pip
  - pyaps3==0.3.5 #0.3.6 CDS downloads fail from MintPy
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - pip:
    - opensarlab_lib
