name: opensarlab_mintpy_recipe_book
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - asf_search 
  - bokeh
  - boto3
  - cartopy
  - contextily
  - dask
  - distributed
  - gdal
  - geopandas
  - h5py
  - hyp3_sdk
  - ipyfilechooser
  - libgdal-hdf5
  - numpy
  - pandas
  - pip
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - matplotlib-base
  - ipympl
  - ipykernel
  - ipython
  - ipyleaflet
  - pip:
    - opensarlab_lib 
    - git+https://github.com/insarlab/MintPy.git@ea0f200
    - git+https://github.com/insarlab/PyAPS.git@6b01c39 #0.3.6 CDS downloads fail from MintPy, install from source until 0.3.7
