name: osl_mintpy
channels:
  - conda-forge
dependencies:
  - python==3.9
  - asf_search 
  - bokeh
  - boto3
  - cartopy=0.22.0=py39h40cae4c_0 # most recent version breaks matplotlib widget and opensarlab_lib AOI_selector
  - dask
  - distributed==2023.4.1 # later versions require Python>=3.10
  - gdal
  - geopandas
  - h5py
  - hyp3_sdk
  - ipympl
  - ipyfilechooser
  - jupyterlab
  - ipywidgets
  - matplotlib-base
  # - mintpy==1.5.1
  - numpy<1.24.0
  - opensarlab_lib
  - pandas
  - pip
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - pip:
    - url-widget
    - git+https://github.com/insarlab/MintPy.git@5683092
