name: opensarlab_mintpy_recipe_book
channels:
  - conda-forge
dependencies:
  - python=3.11
  - asf_search 
  - bokeh
  - boto3
  - cartopy
  - contextily
  - dask
  - distributed
  - gdal
  - geopandas
  - h5py
  - hyp3_sdk
  - ipyfilechooser
  - libgdal-hdf5
  - numpy
  - pandas
  - pip
  - pyaps3==0.3.5 #0.3.6 CDS downloads fail from MintPy
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - pip:
    - opensarlab_lib
    - git+https://github.com/insarlab/MintPy.git@4bbca8c # Install from commit until release > 1.6.1
    - jupyterlab==4.1.5 # needed for matplotlib widgets
    - notebook==7.1.3 # needed for matplotlib widgets
    - matplotlib==3.8.4 # needed for matplotlib widgets
    - ipympl==0.9.2 # needed for matplotlib widgets
    - ipywidgets==8.1.2 # needed for matplotlib widgets
    - jupyterlab-widgets==3.0.10 # needed for matplotlib widgets
    - widgetsnbextension==4.0.10 # needed for matplotlib widgets

