[workspace]
authors = ["Alex-Lewandowski <aflewandowski@alaska.edu>"]
channels = ["conda-forge"]
name = "opensarlab_MintPy_Recipe_Book"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
asf_search = ">=13.0.1,<14"
bokeh = ">=3.10.0,<4"
boto3 = ">=1.43.89,<2"
cartopy = ">=0.25.0,<0.26"
contextily = ">=1.7.1,<2"
dask = ">=2026.8.0,<2027"
distributed = ">=2026.8.0,<2027"
gdal = ">=3.13.3,<4"
geopandas = ">=1.1.4,<2"
h5py = ">=3.16.0,<4"
hyp3_sdk = ">=7.7.8,<8"
ipyfilechooser = ">=0.6.0,<0.7"
libgdal-hdf5 = ">=3.13.3,<4"
numpy = ">=2.5.3,<3"
pandas = ">=3.0.5,<4"
rasterio = ">=1.5.1,<2"
rioxarray = ">=0.23.0,<0.24"
scipy = ">=1.18.0,<2"
shapely = ">=2.1.2,<3"
xarray = ">=2026.7.0,<2027"
matplotlib-base = ">=3.11.1,<4"
ipympl = ">=0.10.0,<0.11"
ipykernel = ">=7.3.0,<8"
ipython = ">=9.17.1,<10"
ipyleaflet = ">=0.20.0,<0.21"
mintpy = "*"
pyaps3 = "*"
jupyterlab = ">=4.6.3,<5"
jupyterlab-myst = ">=2.7.0,<3"

[tasks]
register-kernel = "python -m ipykernel install --user --display-name 'opensarlab_mintpy_recipe_book'"
lab = { cmd = "jupyter lab", depends-on = ["register-kernel"] }

[pypi-dependencies]
opensarlab-lib = ">=0.0.14, <0.0.15"
